export const dataProduct = { 
    id: 1, 
    price: 5.161, 
    currency: {
        name: 'USD',
        symbol: '$'
    },
    obsoleto: false,
    restringuido: false,
    reference: "1SFA184721R9006",
    name: "UCPT750 nVent HOFFMAN Mural, 735x535x270, compacto, 1 puerta de vidrio, sin MP, poliéster, IP66", 
    shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
    largeDescription: "<p><strong>Más información</strong>&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen.</p> <p><strong>Lorem Ipsum</strong>&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen.</p> <p><strong>Lorem Ipsum</strong>&nbsp;es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno est&aacute;ndar de las industrias desde el a&ntilde;o 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido us&oacute; una galer&iacute;a de textos y los mezcl&oacute; de tal manera que logr&oacute; hacer un libro de textos especimen.</p>", 
    slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
    img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
    stock: 0,
    images: [
        "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg",
        "https://www.electricautomationnetwork.com/535142-large_default/3ug4511-1bn20-3ug45111bn20-siemens-reles-de-vigilancia-analog-vigilancia-secuencia-de-fases-3x-160-a-260v-a.jpg",
        "https://www.electricautomationnetwork.com/530592-large_default/3se6604-2ba01-3se66042ba01-siemens-interruptor-magnetico-bloque-de-contactos-25xx88mm-2nc-con-conector-m8-.jpg",
        "https://www.electricautomationnetwork.com/1014529-large_default/080011-legrand-mo-caja-perf-2m.jpg"
    ],
    pdfs: [
        {
            title: 'PDF CATALOGO EATON CONTROL Y AUTOMATIZACION ES.pdf',
            size: '19 MB',
        },
        {
            title: 'PDF CATALOGUE EATON EN.pdf',
            size: '51 MB',
        },
        {
            title: 'PKZM0-0,16 Y7-72730 072730 ES_265346.pdf',
            size: '99 MB',
        },
    ],
    categorization: {
        manufacturer: 'Eaton',
        groupName: 'Eaton Moeller',
        subGroupName: 'Eaton Moeller Contacto Auxiliar'
    },
    descor_ETIM: 'Eaton Addressable micro interface: Cooper,  Addressable,  Micro Output Module,  EN54 Systems',
    etim: {
        "caption":"ETIM for MCOM Cable trunking systems for wall and ceilings (EC000113)",
        "features":{
            "Length (EF001438)":"60 mm",
            "Width (EF000008)":"30 mm",
            "Depth (EF000049)":"60 mm",
            "Material (EF002169)":"Plastic",
            "RAL-number (EF000116)":"9003",
            "Halogen free (EF000025)":"Yes"
        }
    },
    reviews: [
        { order: 1, name: 'Laura G.', nick: '', role:'Barcelona', photoCustomer: 'user2.jpg', rate: 5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 2, name: 'Carlos M.', nick: '', role:'Ciudad de México', photoCustomer: 'user9.jpg', rate: 5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 3, name: 'Fernanda R.', nick: '', role:'Rio de Janeiro', photoCustomer: 'user11.jpg', rate: 4.5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 4, name: 'Johannes L.', nick: '', role:'Düsseldorf', photoCustomer: 'user7.jpg', rate: 5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 5, name: 'Kate S.', nick: '', role:'San Diego', photoCustomer: 'user5.jpg', rate: 5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 6, name: 'Andrew W.', nick: '', role:'Toronto', photoCustomer: 'user4.jpg', rate: 4.5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
        { order: 7, name: 'Amy J.', nick: '', role:'Sunderland', photoCustomer: 'user8.jpg', rate: 5, texto: 'Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor' },
    ],
    box_bestseller: [
        { 
            id: 1, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 2, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 10,
        },
        { 
            id: 3, price: 53.51, 
            referencia: "1SFA184721R9006",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg", 
            stock: 11,
        },
        { 
            id: 4, price: 16.80, 
            referencia: "1SFA184721R9006",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 0,
        },  
        { 
            id: 5, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg", 
            stock: 0,
        },
        { 
            id: 6, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 7, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 0,
        },
        { 
            id: 8, price: 53.51, 
            referencia: "1SFA619403R5073",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg",
            stock: 0, 
        },
        { 
            id: 9, price: 16.80, 
            referencia: "1SFA619551R1051",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 10,
        },  
        { 
            id: 10, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg",
            stock: 0, 
        },
        ,
        { 
            id: 11, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 12, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 0,
        },
        { 
            id: 13, price: 53.51, 
            referencia: "1SFA619403R5073",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg",
            stock: 0, 
        },
        { 
            id: 14, price: 16.80, 
            referencia: "1SFA619551R1051",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 10,
        },  
        { 
            id: 15, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg",
            stock: 0, 
        }    
    ],
    box_viewed_often: [
        { 
            id: 1, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 2, price: 199.46, 
            referencia: "1SFA184721R9006",
            name: "MicroDrive FC51 051 0,75kW, 1x200-240VV, Sin opción de freno, IP20, RFI A1+B1", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/danfoss-drives/variador-vlt-microdrive-fc51-075kw-1x200-240v-ip20-danfoss-132f0003', 
            img: "https://www.electricautomationnetwork.com/172847-large_default/variador-vlt-microdrive-fc51-075kw-1x200-240v-ip20-danfoss-132f0003.jpg", 
            stock: 0,
        },
        { 
            id: 3, price: 53.51, 
            referencia: "1SFA184721R9006",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg", 
            stock: 10,
        },
        { 
            id: 4, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg", 
            stock: 0,
        }, 
        { 
            id: 5, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 0,
        }, 
    ],
    box_bought_together: [
        { 
            id: 1, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 2, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 10,
        },
        { 
            id: 3, price: 53.51, 
            referencia: "1SFA184721R9006",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg", 
            stock: 11,
        },
        { 
            id: 4, price: 16.80, 
            referencia: "1SFA184721R9006",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 0,
        },  
        { 
            id: 5, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg", 
            stock: 0,
        },
        { 
            id: 6, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 7, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 0,
        },
        { 
            id: 8, price: 53.51, 
            referencia: "1SFA619403R5073",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg",
            stock: 0, 
        },
        { 
            id: 9, price: 16.80, 
            referencia: "1SFA619551R1051",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 10,
        },  
        { 
            id: 10, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg",
            stock: 0, 
        },
        ,
        { 
            id: 11, price: 5.16, 
            referencia: "1SFA184721R9006",
            name: "Elemento de contacto 1 NO Montaje frontal Conexión a tornillo", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10', 
            img: "https://www.electricautomationnetwork.com/290586-large_default/contacto-auxiliar-1no-m22-k10-eaton-moeller-216376-m22-k10.jpg", 
            stock: 0,
        },
        { 
            id: 12, price: 0.67, 
            referencia: "1SFA184721R9006",
            name: "Ecartucho fusible, BT, 6 A, AC 500 V, 10 x 38 mm", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec', 
            img: "https://www.electricautomationnetwork.com/640730-large_default/c10g6-eaton-moeller-cartucho-fusible-bt-6-a-ac-500-v-10-x-38-mm-gl-gg-iec.jpg", 
            stock: 0,
        },
        { 
            id: 13, price: 53.51, 
            referencia: "1SFA619403R5073",
            name: "Contactor de potencia Conexión a tornillo 3 polos + 1 NO 9 A 4 kW 400", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc', 
            img: "https://www.electricautomationnetwork.com/296688-large_default/contactor-9a-1no-24vdc-dilm9-1024vcd-eaton-moeller-276705-dilm9-1024vdc.jpg",
            stock: 0, 
        },
        { 
            id: 14, price: 16.80, 
            referencia: "1SFA619551R1051",
            name: "Int. magnetotérmico Home, 1P+N, curva C, 10A", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/eaton-moeller/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n', 
            img: "https://www.electricautomationnetwork.com/832425-large_default/hn-c10-1n-194849-eaton-electric-194849-hn-c10-1n.jpg", 
            stock: 10,
        },  
        { 
            id: 15, price: 76.20, 
            referencia: "1SFA184721R9006",
            name: "Amplificador de fibra, tipo Estándar, PNP, pantalla, tipo de conector, cable", 
            shortDescription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the", 
            slug: '/panasonic/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2', 
            img: "https://www.electricautomationnetwork.com/178555-large_default/fx-101p-cc2-fx101pcc2-panasonic-fx100-amplificador-f-optica-salida-pnp-incluye-cable-cn14ac2.jpg",
            stock: 0, 
        }    
    ]
}